my_site/blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('<int:id>/', views.post_detail, name='post_detail'),
]

my_site/forms/urls.py
from django.urls import path
from . import views

app_name = 'forms'

urlpatterns = [
    path('', views.forms, name='forms'),
    path('forms2', views.forms2, name='forms2'),
    path('forms3', views.forms3, name='forms3'),
]

my_site/my_site/urls.py
from django.contrib import admin
from django.urls import path, include

#imports for images
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls' , namespace='blog')),
    path ('products/',include('products.urls',namespace='products')),
    path ('',include('products.urls',namespace='products')),
    path ('relations/',include('relations.urls',namespace='relations')),
    path ('forms/' , include('forms.urls',namespace='forms'))
] + static(settings.MEDIA_URL , document_root=settings.MEDIA_ROOT)   #this static for images activate

my_site/products/urls.py
from django.urls import path
from . import views

app_name = 'products'

urlpatterns = [
    path('product/', views.product, name='product'),
    path('', views.products, name='products'),
]

my_site/relations/urls.py
from django.urls import path
from . import views

app_name = 'relatons'

urlpatterns = [
    path('', views.relations, name='relations'),
]

my_site/blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User

class Post(models.Model):
    
    class Status(models.TextChoices):
        DRAFT = 'DF', 'Draft'
        PUBLISHED = 'PB', 'Published'
    
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250)
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='blog_posts')
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=2, choices=Status.choices, default=Status.DRAFT)
    
    class Meta:
        ordering = ['-publish']
        indexes = [
            models.Index(fields=['-publish']),
        ]
    
    def __str__(self):
        return self.title

my_site/blog/views.py
from django.shortcuts import render,  get_object_or_404
from .models import Post

def post_list(request):
    posts = Post.objects.all()
    return render(request, 'blog/post/list.html', {'posts': posts})

def post_detail(request, id):
    post = get_object_or_404(Post, id=id, status=Post.Status.PUBLISHED)
    return render(request, 'blog/post/detail.html', {'post': post}) 
    # request is require and then path  and context (dictianary)
    #context use to assign varailbles in htmls pages

my_site/templates/blog/post/detail.html
{% extends "blog/base.html" %}

{% block title %}{{ post.title }}{% endblock %}

{% block content %}
    
    <h1>{{ post.title }}</h1>
    <p class="date">
    Published {{ post.publish }} by {{ post.author }}
    </p>
    {{ post.body|linebreaks }}

{% endblock %}

my_site/templates/blog/post/footer.html
<h2>make you self as you sea  a nav par</h2>

my_site/templates/blog/post/list.html
{% extends "blog/base.html" %}
{%load static %}

{% block title %}My Blog{% endblock %}


{% block content %}
<h1>My Blog</h1>
<!-- <p>helllllllllllllllllllllll</p> -->
<!-- <img src="{%static 'image/1.jpg'%}" alt="">  -->

{% for post in posts %}
<h2>
    <a href="{% url 'blog:post_detail' post.id %}">
        {{ post.title |add:'ahmed hamdy'}}
    </a>
</h2>
<p class="date">
    Published {{ post.publish }} by {{ post.author }}
</p>
{{ post.body|truncatewords:30|linebreaks }}
<hr />
{% endfor %}
{% endblock %}

my_site/templates/blog/post/navbar.html
{% load static %}
<link rel="stylesheet" href="{% static 'css/navbar.css' %}">

<nav>
    <span><a href="{% url 'products:products' %}">Product</a></span>
    <span><a href="{% url 'relations:relations' %}">Relations</a></span>
    <span><a href="{% url 'blog:post_list' %}">Post</a></span>
    <span><a href="{% url 'forms:forms' %}">forms</a></span>
</nav>